import {
  INITIAL_ACCOUNTS, INITIAL_ALIASES, INITIAL_AUDIT_LOGS, INITIAL_KEYS,
  INITIAL_METRICS, INITIAL_MODELS, INITIAL_PROVIDERS, INITIAL_REQUESTS, INITIAL_ROUTES,
} from '../data/mockData';
import type { Account, ModelAlias, ModelConfig, Provider, Route, VirtualKey } from '../types';

let keys=structuredClone(INITIAL_KEYS), providers=structuredClone(INITIAL_PROVIDERS),
accounts=structuredClone(INITIAL_ACCOUNTS), models=structuredClone(INITIAL_MODELS),
routes=structuredClone(INITIAL_ROUTES), aliases=structuredClone(INITIAL_ALIASES);
const ok=<T>(x:T)=>Promise.resolve(x);
const id=(p:string)=>`${p}-${Date.now()}`;

const plugin:any={
 id:'opencode-free',name:'OpenCode Free',version:'0.1.0-demo',plugin_api_major:1,
 sha256:'demo-opencode-free',signature:'verified-demo',status:'enabled',
 provides:[{capability:'provider_adapter',name:'OpenCode Free Adapter'},{capability:'model_source',name:'OpenCode Free Models'}],
 integrations:[{id:'opencode-free',name:'OpenCode Free',description:'Credential-free OpenCode Free integration.',
 provider_adapter:'opencode-free',credential_strategy:null,auth_flow:null,model_source:'opencode-free',
 provider:{base_url:'https://opencode.ai',wire_format:'openai',auth_scheme:'bearer',custom_header_name:null,
 custom_param_name:null,extra_headers:{},timeout_ms:120000,capability_mode:'permissive',models_path:'/models',
 follow_redirects:true,credential_hosts:['opencode.ai']}}],
 ui:{actions:[],settings:[{key:'endpoint',label:'Endpoint',kind:'text',description:'Optional endpoint override.',
 required:false,options:[],default:'https://opencode.ai'}]},
 permissions:{network_hosts:['opencode.ai'],credential_scopes:[],credential_read:false},
 limits:{memory:'64 MiB',wall_time_ms:30000,max_outbound_requests:8,max_http_body:'8 MiB',storage:'none'},
 routing_facts_mode:'cached',routing_facts_refresh_ms:300000,
 packages:[{plugin_id:'opencode-free',version:'0.1.0-demo',package_sha256:'demo-opencode-free',
 package_path:'demo/opencode-free.kxp',signature:'verified-demo',source:'demo',installed_at:'2026-09-21T00:00:00Z'}],
};
let pluginSettings:any={id:plugin.id,settings:plugin.ui.settings.map((s:any)=>({...s,configured:true,value:s.default}))};
const catalog:any={schema_version:1,plugins:[{id:plugin.id,name:plugin.name,
 description:'Credential-free OpenCode integration with model discovery.',publisher:'PrightCord',official:true,
 homepage:'https://github.com/PrightCord/kinetix-plugins',latest_version:plugin.version,artifact_name:'opencode-free.kxp',
 capabilities:['provider_adapter','model_source'],installable:true,install_ready:true,trust_status:'trusted',
 distribution:null,note:'Demo catalog entry'}]};

export const DemoKinetix:any={
 me:()=>ok({authenticated:true,user:'demo@kinetix.local'}),login:(_:string)=>ok({ok:true,user:'demo@kinetix.local'}),
 logout:()=>ok({ok:true}),changePassword:()=>ok({ok:true,note:'Demo mode: not persisted.'}),
 overview:()=>ok({...INITIAL_METRICS}),
 exports:()=>ok({dir:'/var/lib/kinetix/exports (demo)',retention_days:30,
 files:[{name:'usage-2026-09-20.jsonl',day:'2026-09-20',kind:'jsonl',bytes:48210},
 {name:'usage-2026-09-20.csv',day:'2026-09-20',kind:'csv',bytes:19934}],
 days:[{day:'2026-09-20',requests:4120,tokens:8390000},{day:'2026-09-19',requests:3710,tokens:7120000}]}),
 exportDay:(day?:string)=>ok({ok:true,day:day??'2026-09-20',jsonl:'demo.jsonl',csv:'demo.csv'}),
 deleteExport:()=>ok({ok:true}),
 keys:()=>ok(structuredClone(keys)),
 createKey:(b:any)=>{const k:VirtualKey={id:id('key'),key:'sk-kinetix-demo-generated',name:b.name,owner:b.owner,tag:b.tag,
 allowedModels:b.allowed_models??['*'],allowedProviders:[],rpmLimit:b.rpm_limit??0,tpmLimit:b.tpm_limit??0,
 dailyBudget:b.daily_budget??0,monthlyBudget:b.monthly_budget??0,currentDailySpend:0,currentMonthlySpend:0,
 createdAt:new Date().toISOString(),expiresAt:null,status:'active',allowedIps:[],totalRequests:0,totalTokens:0};keys=[k,...keys];return ok({key:k,fullKey:k.key})},
 updateKey:(x:string,b:any)=>{keys=keys.map(k=>k.id===x?{...k,status:b.status??k.status,allowedIps:b.allowed_ips??k.allowedIps}:k);return ok({ok:true})},
 deleteKey:(x:string)=>{keys=keys.filter(k=>k.id!==x);return ok({ok:true})},
 providers:()=>ok(structuredClone(providers)),getProvider:(x:string)=>ok(structuredClone(providers.find(p=>p.id===x)??providers[0])),
 createProvider:(b:any)=>{providers.push({id:id('prov'),name:b.name,baseUrl:b.base_url,wireFormat:b.wire_format,authScheme:b.auth_scheme,
 status:'healthy',modelsCount:0,accountsCount:0,timeoutMs:b.timeout_ms??120000,capabilityMode:b.capability_mode??'permissive',lastPingMs:24,
 customHeaderName:b.custom_header_name??undefined,customParamName:b.custom_param_name??undefined,extraHeaders:b.extra_headers??{},
 modelsPath:b.models_path??undefined,credentialHosts:b.credential_hosts??'',followRedirects:!!b.follow_redirects,allowInsecureTls:!!b.allow_insecure_tls,
 wirePlugin:b.wire_plugin??'',credentialPlugin:b.credential_plugin??'',modelSourcePlugin:b.model_source_plugin??''} as Provider);return ok({ok:true})},
 updateProvider:(x:string,b:any)=>{providers=providers.map(p=>p.id===x?{...p,name:b.name??p.name,baseUrl:b.base_url??p.baseUrl}:p);return ok({ok:true})},
 deleteProvider:(x:string)=>{providers=providers.filter(p=>p.id!==x);models=models.filter(m=>m.providerId!==x);accounts=accounts.filter(a=>a.providerId!==x);return ok({ok:true})},
 validateProvider:()=>ok({valid:true,problems:[],warnings:['Demo validation only.'],outbound_security:'demo'}),
 discover:(x:string)=>ok(models.filter(m=>m.providerId===x).map(m=>({id:m.upstreamModelId,display_name:m.displayName,context_window:m.contextWindow,max_output_tokens:m.maxOutputTokens,already_imported:true}))),
 test:()=>ok({ok:true,status:200,latency_ms:127,response_preview:'Demo provider test passed.'}),
 models:()=>ok(structuredClone(models)),validateModel:()=>ok({valid:true,problems:[],warnings:['Demo validation only.']}),
 createModel:(p:string,b:any)=>{const pv=providers.find(x=>x.id===p);models.push({id:id('model'),providerId:p,providerName:pv?.name??p,
 upstreamModelId:b.upstream_id,displayName:b.display_name,enabled:b.enabled!==false,contextWindow:b.context_window??0,maxOutputTokens:b.max_output_tokens??0,
 capabilities:{text:!!b.capabilities?.text,vision:!!b.capabilities?.vision,reasoning:!!b.capabilities?.reasoning,toolCalling:!!b.capabilities?.tool_calling,audio:!!b.capabilities?.audio},
 prices:{inputPer1M:b.prices?.input_per_1m??0,outputPer1M:b.prices?.output_per_1m??0,cachedPer1M:b.prices?.cached_per_1m??0,thinkingPer1M:b.prices?.thinking_per_1m??0},
 parameters:b.parameters??{},thinkingMap:b.thinking_map??{scale:'off',mappedField:''}} as ModelConfig);return ok({ok:true})},
 updateModel:(x:string,b:any)=>{models=models.map(m=>m.id===x?{...m,displayName:b.display_name??m.displayName,upstreamModelId:b.upstream_id??m.upstreamModelId}:m);return ok({ok:true})},
 deleteModel:(x:string)=>{models=models.filter(m=>m.id!==x);return ok({ok:true})},
 accounts:()=>ok(structuredClone(accounts)),validateAccount:()=>ok({valid:true,problems:[]}),
 createAccount:(b:any)=>{const p=providers.find(x=>x.id===b.provider_id);accounts.push({id:id('acc'),providerId:b.provider_id,providerName:p?.name??b.provider_id,
 label:b.label,keyMasked:'demo••••',status:'healthy',quotaType:b.quota_type??'none',softQuotaSpendLimit:b.soft_quota_usd??undefined,currentSpend:0,
 requestsCount:0,tokensCount:0,priority:b.priority??1} as Account);return ok({ok:true})},
 updateAccount:(x:string,b:any)=>{accounts=accounts.map(a=>a.id===x?{...a,label:b.label??a.label,priority:b.priority??a.priority}:a);return ok({ok:true})},
 deleteAccount:(x:string)=>{accounts=accounts.filter(a=>a.id!==x);return ok({ok:true})},resetAccount:()=>ok({ok:true}),
 routes:()=>ok(structuredClone(routes)),createRoute:(b:any)=>{routes.push({id:id('route'),name:b.name,description:b.description??'',selectionStrategy:b.strategy??'priority',
 fallbackTriggers:b.fallback_triggers??{on429:true,onQuota:true,on5xx:true,onTimeout:true},targets:[],continuityPolicy:b.continuity_policy??'strip',
 portabilityPolicy:b.portability_policy??'strip_with_warning',cacheAffinity:!!b.cache_affinity,stickyRouting:!!b.sticky_routing,totalHops:0,status:'active'} as Route);return ok({ok:true})},
 updateRoute:(x:string,b:any)=>{routes=routes.map(r=>r.id===x?{...r,name:b.name??r.name,description:b.description??r.description}:r);return ok({ok:true})},
 deleteRoute:(x:string)=>{routes=routes.filter(r=>r.id!==x);return ok({ok:true})},dryRunRoute:(m:string)=>ok({model:m,selected:routes[0]?.targets[0]??null,trace:['demo-selection']}),
 aliases:()=>ok(structuredClone(aliases)),createAlias:(b:any)=>{aliases.push({id:id('alias'),aliasName:b.alias,targetType:b.target_type,targetId:b.target_id,targetDisplayName:b.target_id,description:b.description??''} as ModelAlias);return ok({ok:true})},
 deleteAlias:(x:string)=>{aliases=aliases.filter(a=>a.id!==x);return ok({ok:true})},
 requests:()=>ok(structuredClone(INITIAL_REQUESTS)),liveRequests:()=>ok(INITIAL_REQUESTS.slice(0,3).map((r:any,i)=>({requestId:r.requestId,keyName:r.virtualKeyName,frontend:r.clientFormat,
 requestedModel:r.requestedModel,routeName:r.routeName??null,phase:i===0?'streaming':'done',commitState:r.commitState,fallbackHops:r.fallbackHops,retryCount:r.retryCount,
 inputTokens:r.inputTokens,outputTokens:r.outputTokens,status:r.status,latencyMs:r.latencyMs,ttftMs:r.ttftMs,finished:i!==0}))),
 plugins:()=>ok([structuredClone(plugin)]),pluginCatalog:()=>ok(structuredClone(catalog)),plugin:()=>ok(structuredClone(plugin)),
 pluginPermissions:()=>ok({id:plugin.id,requested:plugin.permissions,approved:[]}),pluginSettings:()=>ok(structuredClone(pluginSettings)),
 updatePluginSettings:(_:string,v:any)=>{pluginSettings.settings=pluginSettings.settings.map((s:any)=>({...s,value:v[s.key]??s.value,configured:true}));return ok(structuredClone(pluginSettings))},
 previewCatalogPlugin:()=>ok({id:plugin.id,name:plugin.name,current_version:plugin.version,target_version:plugin.version,sha256:plugin.sha256,signature:'verified',source:'demo',
 permissions:plugin.permissions,permission_diff:{network_hosts:{added:[],removed:[]},credential_scopes:{added:[],removed:[]},credential_read:{from:false,to:false,changed:false}},provides:plugin.provides}),
 installCatalogPlugin:()=>ok({id:plugin.id,version:plugin.version,sha256:plugin.sha256,signature:'verified',provides:plugin.provides,enabled:true,note:'Demo install completed.'}),
 installPlugin:()=>ok({id:plugin.id,version:plugin.version,sha256:plugin.sha256,signature:'verified',provides:plugin.provides,enabled:true}),
 setupPluginIntegrationProvider:()=>{if(!providers.some(p=>p.id==='prov-opencode-free'))providers.push({id:'prov-opencode-free',name:'OpenCode Free',baseUrl:'https://opencode.ai',
 wireFormat:'plugin',authScheme:'bearer',status:'healthy',modelsCount:0,accountsCount:0,timeoutMs:120000,capabilityMode:'permissive',lastPingMs:31,wirePlugin:'opencode-free',modelSourcePlugin:'opencode-free'} as Provider);
 return ok({id:'prov-opencode-free',name:'OpenCode Free',created:true})},
 startPluginAuth:()=>ok({authorize_url:'#demo-no-auth-required',state:'demo',expires_in_secs:300}),approvePluginPermissions:()=>ok({ok:true,id:plugin.id,approved:[]}),
 revokePluginPermission:(_:string,p:string)=>ok({ok:true,id:plugin.id,revoked:p,enabled:true}),enablePlugin:()=>ok({ok:true,id:plugin.id,enabled:true}),disablePlugin:()=>ok({ok:true,id:plugin.id,enabled:false}),
 validatePlugin:()=>ok({ok:true,id:plugin.id,provides:plugin.provides}),previewPluginRollback:()=>ok({id:plugin.id,current_version:plugin.version,target_version:plugin.version,package_sha256:plugin.sha256,
 signature:'verified',source:'demo',permissions:plugin.permissions,permission_diff:{network_hosts:{added:[],removed:[]},credential_scopes:{added:[],removed:[]},credential_read:{from:false,to:false,changed:false}},provides:plugin.provides}),
 rollbackPlugin:()=>ok({id:plugin.id,version:plugin.version,sha256:plugin.sha256,signature:'verified',provides:plugin.provides,enabled:true}),
 reinstallPluginPackage:()=>ok({id:plugin.id,version:plugin.version,sha256:plugin.sha256,signature:'verified',provides:plugin.provides,enabled:true}),
 removePlugin:()=>ok({ok:true,id:plugin.id}),audit:()=>ok(structuredClone(INITIAL_AUDIT_LOGS)),
};
