import type { ScenarioState } from '../types.ts';
import { healthyScenario } from './healthy.ts';

export const complexFallbackRouteScenario: ScenarioState = {
  ...healthyScenario,
  id: 'complex-fallback-route',
  name: 'Complex Fallback Route Chain',
  description: 'Multi-tiered 6-hop fallback cascade across 4 independent providers with sticky cache affinity and dynamic latency thresholds.',
  badge: '6-Hop Fallback',
  badgeColor: 'blue',
  routes: [
    {
      id: 'route-cascade-ultra',
      name: 'ultra-reliable-chat',
      description: 'Zero-drop SLA chain: Claude 3.7 -> Claude 3.5 -> GPT-4o -> Gemini 2.0 Flash -> DeepSeek V3 -> Llama 3.3',
      selection_strategy: 'priority',
      fallback_triggers: {
        on_429: true,
        on_quota: true,
        on_5xx: true,
        on_timeout: true,
      },
      targets: [
        {
          provider_id: 'prov-anthropic',
          account_id: 'acc-anthropic-primary',
          model: 'claude-3-7-sonnet-20250219',
          priority: 1,
          weight: 100,
          timeout_ms: 12000,
        },
        {
          provider_id: 'prov-anthropic',
          account_id: 'acc-anthropic-backup',
          model: 'claude-3-5-haiku-20241022',
          priority: 2,
          weight: 100,
          timeout_ms: 8000,
        },
        {
          provider_id: 'prov-openai',
          account_id: 'acc-openai-primary',
          model: 'gpt-4o',
          priority: 3,
          weight: 100,
          timeout_ms: 15000,
        },
        {
          provider_id: 'prov-google-ai',
          account_id: 'acc-google-gemini',
          model: 'gemini-2.0-flash',
          priority: 4,
          weight: 100,
          timeout_ms: 10000,
        },
        {
          provider_id: 'prov-openai',
          account_id: 'acc-openai-secondary',
          model: 'gpt-4o-mini',
          priority: 5,
          weight: 100,
          timeout_ms: 8000,
        },
        {
          provider_id: 'prov-anthropic',
          account_id: 'acc-anthropic-backup',
          model: 'claude-3-5-haiku-20241022',
          priority: 6,
          weight: 100,
          timeout_ms: 5000,
        },
      ],
      portability_policy: 'strip_with_warning',
      cache_affinity: true,
      sticky_routing: true,
      total_hops: 48,
      status: 'active',
      enabled: true,
    },
    ...healthyScenario.routes,
  ],
  requests: [
    {
      request_id: 'req-chain-hop-3',
      client_format: 'openai',
      virtual_key_id: 'key-prod-app',
      virtual_key_name: 'Production Core Backend',
      virtual_key_tag: 'core-infra',
      requested_model: 'ultra-reliable-chat',
      actual_model: 'gemini-2.0-flash',
      route_id: 'route-cascade-ultra',
      route_name: 'ultra-reliable-chat',
      upstream_provider: 'Google Gemini Gateway',
      upstream_account: 'Google Vertex / AI Studio Paid',
      input_tokens: 3400,
      output_tokens: 610,
      total_tokens: 4010,
      cost_usd: 0.000584,
      status: 200,
      latency_ms: 2450,
      ttft_ms: 1890,
      fallback_hops: 3,
      fallback_path: [
        'Hop 1: prov-anthropic / claude-3-7 -> 429 Rate Limit',
        'Hop 2: prov-anthropic / haiku -> 504 Gateway Timeout',
        'Hop 3: prov-openai / gpt-4o -> 503 Service Unavailable',
        'Hop 4: prov-google-ai / gemini-2.0-flash -> 200 OK (Committed)',
      ],
      retry_count: 3,
      user_agent: 'kinetix-sdk-go/1.4.0',
      client_ip: '10.240.1.18',
      commit_state: 'committed',
      timestamp: new Date().toISOString(),
    },
    ...healthyScenario.requests,
  ],
};
