import type { ScenarioState } from '../types.ts';

export const emptyScenario: ScenarioState = {
  id: 'empty',
  name: 'Empty Gateway',
  description: 'Fresh installation with zero virtual keys, providers, routes, or traffic history.',
  badge: 'Empty',
  badgeColor: 'blue',
  user: 'admin',
  publicBaseUrl: 'http://localhost:3000',
  lifecycleSettings: {
    reconciliation_interval_secs: 21600,
    pricing_sync_interval_secs: 43200,
    jitter_secs: 900,
    probe_freshness_secs: 86400,
  },
  keys: [],
  providers: [],
  accounts: [],
  models: [],
  routes: [],
  aliases: [],
  requests: [],
  liveRequests: [],
  auditLogs: [],
  metrics: {
    active_keys: 0,
    total_keys: 0,
    total_requests: 0,
    total_tokens: 0,
    active_routes: 0,
    total_routes: 0,
    healthy_providers: 0,
    total_providers: 0,
    healthy_accounts: 0,
    total_accounts: 0,
    requests_today: 0,
    requests_this_month: 0,
    tokens_today: 0,
    tokens_this_month: 0,
    total_spend_usd: 0,
    spend_today_usd: 0,
    spend_this_month_usd: 0,
    avg_latency_ms: 0,
    avg_ttft_ms: 0,
    error_rate: 0,
    active_streams: 0,
    circuit_breakers_open: 0,
    cache_hit_ratio: 0,
  },
  runtimeHealth: {
    window: '1h',
    telemetry: [],
    provider_circuits: [],
    quota: [],
    dropped: { queue: 0, persistence: 0 },
  },
  plugins: [],
  exportFiles: [],
  exportDays: [],
};
