import type { ScenarioState } from '../types.ts';

export const healthyScenario: ScenarioState = {
  id: 'healthy',
  name: 'Nominal Operations',
  description: 'All upstream providers connected, accounts healthy, sub-300ms latency, zero circuits open.',
  badge: 'Healthy',
  badgeColor: 'green',
  user: 'admin',
  publicBaseUrl: 'https://gateway.kinetix.internal',
  lifecycleSettings: {
    reconciliation_interval_secs: 21600,
    pricing_sync_interval_secs: 43200,
    jitter_secs: 900,
    probe_freshness_secs: 86400,
  },
  keys: [
    {
      id: 'key-prod-app',
      name: 'Production Core Backend',
      key_hash: 'kinetix_live_prod_core_8f1b2c',
      owner: 'Platform Team',
      tag: 'core-infra',
      allowed_models: ['*'],
      allowed_providers: [],
      rpm_limit: 5000,
      tpm_limit: 500000,
      daily_budget: 250.0,
      monthly_budget: 5000.0,
      current_daily_spend: 42.15,
      current_monthly_spend: 980.4,
      status: 'active',
      allowed_ips: ['10.0.0.0/16', '192.168.1.0/24'],
      created_at: '2026-09-01T08:00:00Z',
      expires_at: null,
      total_requests: 184200,
      total_tokens: 92450000,
    },
    {
      id: 'key-ai-agent',
      name: 'Coding Agent Worker',
      key_hash: 'kinetix_live_agent_3c4d5e',
      owner: 'DevEx Engineering',
      tag: 'agentic-loop',
      allowed_models: ['claude-3-7-sonnet', 'gpt-4o', 'route-fast-interactive'],
      allowed_providers: ['prov-anthropic', 'prov-openai'],
      rpm_limit: 1200,
      tpm_limit: 200000,
      daily_budget: 150.0,
      monthly_budget: 3000.0,
      current_daily_spend: 28.5,
      current_monthly_spend: 640.2,
      status: 'active',
      allowed_ips: [],
      created_at: '2026-09-12T14:30:00Z',
      expires_at: '2026-12-31T23:59:59Z',
      total_requests: 94100,
      total_tokens: 41200000,
    },
    {
      id: 'key-batch-analytics',
      name: 'Nightly Analytics Pipeline',
      key_hash: 'kinetix_live_analytics_9f0a1b',
      owner: 'Data Science',
      tag: 'batch-etl',
      allowed_models: ['claude-3-5-haiku', 'gpt-4o-mini'],
      allowed_providers: [],
      rpm_limit: 300,
      tpm_limit: 100000,
      daily_budget: 50.0,
      monthly_budget: 800.0,
      current_daily_spend: 3.12,
      current_monthly_spend: 114.5,
      status: 'active',
      allowed_ips: [],
      created_at: '2026-09-15T10:00:00Z',
      expires_at: null,
      total_requests: 31200,
      total_tokens: 18900000,
    },
  ],
  providers: [
    {
      id: 'prov-anthropic',
      name: 'Anthropic Direct',
      base_url: 'https://api.anthropic.com',
      wire_format: 'anthropic',
      auth_scheme: 'custom_header',
      custom_header_name: 'x-api-key',
      extra_headers: { 'anthropic-version': '2023-06-01' },
      models_path: '/v1/models',
      timeout_ms: 60000,
      capability_mode: 'strict',
      credential_hosts: 'api.anthropic.com',
      follow_redirects: true,
      allow_insecure_tls: false,
      status: 'healthy',
      last_ping_ms: 124,
      models_count: 3,
      accounts_count: 2,
      credential_mode: 'manual',
    },
    {
      id: 'prov-openai',
      name: 'OpenAI Production',
      base_url: 'https://api.openai.com',
      wire_format: 'openai',
      auth_scheme: 'bearer',
      extra_headers: {},
      models_path: '/v1/models',
      timeout_ms: 60000,
      capability_mode: 'strict',
      credential_hosts: 'api.openai.com',
      follow_redirects: true,
      allow_insecure_tls: false,
      status: 'healthy',
      last_ping_ms: 108,
      models_count: 3,
      accounts_count: 2,
      credential_mode: 'manual',
    },
    {
      id: 'prov-google-ai',
      name: 'Google Gemini Gateway',
      base_url: 'https://generativelanguage.googleapis.com',
      wire_format: 'gemini',
      auth_scheme: 'custom_header',
      custom_header_name: 'x-goog-api-key',
      extra_headers: {},
      models_path: '/v1beta/models',
      timeout_ms: 90000,
      capability_mode: 'strict',
      credential_hosts: 'generativelanguage.googleapis.com',
      follow_redirects: true,
      allow_insecure_tls: false,
      status: 'healthy',
      last_ping_ms: 142,
      models_count: 2,
      accounts_count: 1,
      credential_mode: 'manual',
    },
  ],
  accounts: [
    {
      id: 'acc-anthropic-primary',
      provider_id: 'prov-anthropic',
      provider_name: 'Anthropic Direct',
      label: 'Anthropic Tier 4 Primary',
      key_masked: 'sk-ant-api03-••••••••4a8f',
      status: 'healthy',
      quota_type: 'none',
      soft_quota_usd: 500,
      current_spend: 84.2,
      requests_count: 8240,
      tokens_count: 4210000,
      priority: 10,
      weight: 80,
      credential_kind: 'api_key',
      credential_summary: 'Standard Enterprise Key',
    },
    {
      id: 'acc-anthropic-backup',
      provider_id: 'prov-anthropic',
      provider_name: 'Anthropic Direct',
      label: 'Anthropic Standby Account',
      key_masked: 'sk-ant-api03-••••••••9c12',
      status: 'healthy',
      quota_type: 'none',
      soft_quota_usd: 200,
      current_spend: 12.4,
      requests_count: 940,
      tokens_count: 512000,
      priority: 20,
      weight: 20,
      credential_kind: 'api_key',
      credential_summary: 'Backup Account Pool',
    },
    {
      id: 'acc-openai-primary',
      provider_id: 'prov-openai',
      provider_name: 'OpenAI Production',
      label: 'OpenAI Org Production',
      key_masked: 'sk-proj-••••••••99ab',
      status: 'healthy',
      quota_type: 'none',
      soft_quota_usd: 400,
      current_spend: 64.8,
      requests_count: 6180,
      tokens_count: 3890000,
      priority: 10,
      weight: 70,
      credential_kind: 'api_key',
      credential_summary: 'Dedicated Production Key',
    },
    {
      id: 'acc-openai-secondary',
      provider_id: 'prov-openai',
      provider_name: 'OpenAI Production',
      label: 'OpenAI Failover Org',
      key_masked: 'sk-proj-••••••••23dc',
      status: 'healthy',
      quota_type: 'none',
      soft_quota_usd: 200,
      current_spend: 8.9,
      requests_count: 620,
      tokens_count: 410000,
      priority: 20,
      weight: 30,
      credential_kind: 'api_key',
      credential_summary: 'Failover Pool',
    },
    {
      id: 'acc-google-gemini',
      provider_id: 'prov-google-ai',
      provider_name: 'Google Gemini Gateway',
      label: 'Google Vertex / AI Studio Paid',
      key_masked: 'AIzaSy••••••••88ef',
      status: 'healthy',
      quota_type: 'none',
      soft_quota_usd: 300,
      current_spend: 18.2,
      requests_count: 1410,
      tokens_count: 1240000,
      priority: 10,
      weight: 100,
      credential_kind: 'api_key',
      credential_summary: 'Pay-as-you-go Plan',
    },
  ],
  models: [
    {
      id: 'model-claude-3-7-sonnet',
      provider_id: 'prov-anthropic',
      provider_name: 'Anthropic Direct',
      upstream_id: 'claude-3-7-sonnet-20250219',
      display_name: 'Claude 3.7 Sonnet',
      enabled: true,
      context_window: 200000,
      max_output_tokens: 8192,
      capabilities: {
        text: true,
        vision: true,
        reasoning: true,
        tool_calling: true,
        structured_output: true,
        audio: false,
      },
      prices: {
        input_per_1m: 3.0,
        output_per_1m: 15.0,
        cached_per_1m: 0.3,
        cache_write_per_1m: 3.75,
        thinking_per_1m: 15.0,
      },
      thinking_map: {
        levels: { low: 2048, medium: 8192, high: 16384 },
        mode: 'level',
      },
      transport_override: null,
      canonical_identity: {
        status: 'resolved',
        upstream_model_id: 'claude-3-7-sonnet-20250219',
        canonical_model_id: 'claude-3-7-sonnet',
        match: 'exact',
        source: 'models.dev',
      },
      model_type: 'chat',
      execution_supported: true,
      reconciliation: {
        status: 'unchanged',
        checked_at: '2026-09-30T12:00:00Z',
        last_success_at: '2026-09-30T12:00:00Z',
        diff: [],
        pinned_fields: [],
      },
    },
    {
      id: 'model-claude-3-5-haiku',
      provider_id: 'prov-anthropic',
      provider_name: 'Anthropic Direct',
      upstream_id: 'claude-3-5-haiku-20241022',
      display_name: 'Claude 3.5 Haiku',
      enabled: true,
      context_window: 200000,
      max_output_tokens: 8192,
      capabilities: {
        text: true,
        vision: false,
        reasoning: false,
        tool_calling: true,
        structured_output: true,
        audio: false,
      },
      prices: {
        input_per_1m: 0.8,
        output_per_1m: 4.0,
        cached_per_1m: 0.08,
        cache_write_per_1m: 1.0,
        thinking_per_1m: null,
      },
      transport_override: null,
      canonical_identity: {
        status: 'resolved',
        upstream_model_id: 'claude-3-5-haiku-20241022',
        canonical_model_id: 'claude-3-5-haiku',
        match: 'exact',
        source: 'models.dev',
      },
      model_type: 'chat',
      execution_supported: true,
      reconciliation: {
        status: 'unchanged',
        checked_at: '2026-09-30T12:00:00Z',
        last_success_at: '2026-09-30T12:00:00Z',
        diff: [],
        pinned_fields: [],
      },
    },
    {
      id: 'model-gpt-4o',
      provider_id: 'prov-openai',
      provider_name: 'OpenAI Production',
      upstream_id: 'gpt-4o',
      display_name: 'GPT-4o Omnimodel',
      enabled: true,
      context_window: 128000,
      max_output_tokens: 16384,
      capabilities: {
        text: true,
        vision: true,
        reasoning: false,
        tool_calling: true,
        structured_output: true,
        audio: true,
      },
      prices: {
        input_per_1m: 2.5,
        output_per_1m: 10.0,
        cached_per_1m: 1.25,
        cache_write_per_1m: null,
        thinking_per_1m: null,
      },
      transport_override: null,
      canonical_identity: {
        status: 'resolved',
        upstream_model_id: 'gpt-4o',
        canonical_model_id: 'gpt-4o',
        match: 'exact',
        source: 'models.dev',
      },
      model_type: 'chat',
      execution_supported: true,
      reconciliation: {
        status: 'unchanged',
        checked_at: '2026-09-30T12:00:00Z',
        last_success_at: '2026-09-30T12:00:00Z',
        diff: [],
        pinned_fields: [],
      },
    },
    {
      id: 'model-gpt-4o-mini',
      provider_id: 'prov-openai',
      provider_name: 'OpenAI Production',
      upstream_id: 'gpt-4o-mini',
      display_name: 'GPT-4o Mini',
      enabled: true,
      context_window: 128000,
      max_output_tokens: 16384,
      capabilities: {
        text: true,
        vision: true,
        reasoning: false,
        tool_calling: true,
        structured_output: true,
        audio: false,
      },
      prices: {
        input_per_1m: 0.15,
        output_per_1m: 0.6,
        cached_per_1m: 0.075,
        cache_write_per_1m: null,
        thinking_per_1m: null,
      },
      transport_override: null,
      canonical_identity: {
        status: 'resolved',
        upstream_model_id: 'gpt-4o-mini',
        canonical_model_id: 'gpt-4o-mini',
        match: 'exact',
        source: 'models.dev',
      },
      model_type: 'chat',
      execution_supported: true,
      reconciliation: {
        status: 'unchanged',
        checked_at: '2026-09-30T12:00:00Z',
        last_success_at: '2026-09-30T12:00:00Z',
        diff: [],
        pinned_fields: [],
      },
    },
    {
      id: 'model-gemini-2-flash',
      provider_id: 'prov-google-ai',
      provider_name: 'Google Gemini Gateway',
      upstream_id: 'gemini-2.0-flash',
      display_name: 'Gemini 2.0 Flash',
      enabled: true,
      context_window: 1048576,
      max_output_tokens: 8192,
      capabilities: {
        text: true,
        vision: true,
        reasoning: true,
        tool_calling: true,
        structured_output: true,
        audio: true,
      },
      prices: {
        input_per_1m: 0.1,
        output_per_1m: 0.4,
        cached_per_1m: 0.025,
        cache_write_per_1m: null,
        thinking_per_1m: 0.4,
      },
      transport_override: null,
      canonical_identity: {
        status: 'resolved',
        upstream_model_id: 'gemini-2.0-flash',
        canonical_model_id: 'gemini-2.0-flash',
        match: 'exact',
        source: 'models.dev',
      },
      model_type: 'chat',
      execution_supported: true,
      reconciliation: {
        status: 'unchanged',
        checked_at: '2026-09-30T12:00:00Z',
        last_success_at: '2026-09-30T12:00:00Z',
        diff: [],
        pinned_fields: [],
      },
    },
  ],
  routes: [
    {
      id: 'route-interactive-fast',
      name: 'fast-interactive',
      description: 'Ultra low-latency route targeting Claude 3.7 with immediate failover to GPT-4o on error.',
      selection_strategy: 'priority',
      fallback_triggers: {
        on_429: true,
        on_quota: true,
        on_5xx: true,
        on_timeout: true,
      },
      targets: [
        {
          provider_id: 'prov-anthropic',
          account_id: 'acc-anthropic-primary',
          model: 'claude-3-7-sonnet-20250219',
          priority: 1,
          weight: 100,
          timeout_ms: 15000,
        },
        {
          provider_id: 'prov-openai',
          account_id: 'acc-openai-primary',
          model: 'gpt-4o',
          priority: 2,
          weight: 100,
          timeout_ms: 20000,
        },
      ],
      portability_policy: 'strip_with_warning',
      cache_affinity: true,
      sticky_routing: true,
      total_hops: 12,
      status: 'active',
      enabled: true,
    },
    {
      id: 'route-economy-batch',
      name: 'economy-batch',
      description: 'Cost-optimized routing between Gemini Flash, Claude Haiku, and GPT-4o Mini.',
      selection_strategy: 'lowest_cost',
      fallback_triggers: {
        on_429: true,
        on_quota: true,
        on_5xx: true,
        on_timeout: true,
      },
      targets: [
        {
          provider_id: 'prov-google-ai',
          account_id: 'acc-google-gemini',
          model: 'gemini-2.0-flash',
          priority: 1,
          weight: 50,
          timeout_ms: 30000,
        },
        {
          provider_id: 'prov-openai',
          account_id: 'acc-openai-primary',
          model: 'gpt-4o-mini',
          priority: 2,
          weight: 30,
          timeout_ms: 30000,
        },
        {
          provider_id: 'prov-anthropic',
          account_id: 'acc-anthropic-primary',
          model: 'claude-3-5-haiku-20241022',
          priority: 3,
          weight: 20,
          timeout_ms: 30000,
        },
      ],
      portability_policy: 'strip_with_warning',
      cache_affinity: true,
      sticky_routing: false,
      total_hops: 3,
      status: 'active',
      enabled: true,
    },
  ],
  aliases: [
    {
      id: 'alias-default',
      alias: 'default',
      target_type: 'route',
      target_id: 'route-interactive-fast',
      description: 'Default catch-all route for unconfigured clients',
    },
    {
      id: 'alias-fast',
      alias: 'fast',
      target_type: 'model',
      target_id: 'claude-3-5-haiku',
      description: 'Quick alias pointing directly to Haiku',
    },
  ],
  requests: [
    {
      request_id: 'req-live-001',
      client_format: 'openai',
      virtual_key_id: 'key-prod-app',
      virtual_key_name: 'Production Core Backend',
      virtual_key_tag: 'core-infra',
      requested_model: 'fast-interactive',
      actual_model: 'claude-3-7-sonnet-20250219',
      route_id: 'route-interactive-fast',
      route_name: 'fast-interactive',
      upstream_provider: 'Anthropic Direct',
      upstream_account: 'Anthropic Tier 4 Primary',
      input_tokens: 1420,
      output_tokens: 412,
      total_tokens: 1832,
      cost_usd: 0.01044,
      status: 200,
      latency_ms: 642,
      ttft_ms: 184,
      fallback_hops: 0,
      fallback_path: [],
      retry_count: 0,
      user_agent: 'openai-node/4.52.0',
      client_ip: '10.0.4.12',
      commit_state: 'committed',
      timestamp: new Date(Date.now() - 1000 * 25).toISOString(),
    },
    {
      request_id: 'req-live-002',
      client_format: 'anthropic',
      virtual_key_id: 'key-ai-agent',
      virtual_key_name: 'Coding Agent Worker',
      virtual_key_tag: 'agentic-loop',
      requested_model: 'claude-3-7-sonnet',
      actual_model: 'claude-3-7-sonnet-20250219',
      route_id: 'route-interactive-fast',
      route_name: 'fast-interactive',
      upstream_provider: 'Anthropic Direct',
      upstream_account: 'Anthropic Tier 4 Primary',
      input_tokens: 8400,
      output_tokens: 1250,
      total_tokens: 9650,
      cost_usd: 0.04395,
      status: 200,
      latency_ms: 1420,
      ttft_ms: 220,
      fallback_hops: 0,
      fallback_path: [],
      retry_count: 0,
      user_agent: 'claude-code/0.2.29',
      client_ip: '192.168.1.104',
      commit_state: 'committed',
      timestamp: new Date(Date.now() - 1000 * 95).toISOString(),
    },
    {
      request_id: 'req-live-003',
      client_format: 'openai',
      virtual_key_id: 'key-batch-analytics',
      virtual_key_name: 'Nightly Analytics Pipeline',
      virtual_key_tag: 'batch-etl',
      requested_model: 'economy-batch',
      actual_model: 'gemini-2.0-flash',
      route_id: 'route-economy-batch',
      route_name: 'economy-batch',
      upstream_provider: 'Google Gemini Gateway',
      upstream_account: 'Google Vertex / AI Studio Paid',
      input_tokens: 31200,
      output_tokens: 840,
      total_tokens: 32040,
      cost_usd: 0.003456,
      status: 200,
      latency_ms: 810,
      ttft_ms: 195,
      fallback_hops: 0,
      fallback_path: [],
      retry_count: 0,
      user_agent: 'python-requests/2.31.0',
      client_ip: '10.0.12.88',
      commit_state: 'committed',
      timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    },
  ],
  liveRequests: [
    {
      request_id: 'req-live-stream-01',
      virtual_key_name: 'Production Core Backend',
      client_format: 'openai',
      requested_model: 'fast-interactive',
      route_name: 'fast-interactive',
      phase: 'streaming',
      commit_state: 'committed',
      fallback_hops: 0,
      retry_count: 0,
      input_tokens: 1250,
      output_tokens: 184,
      status: 200,
      latency_ms: 412,
      ttft_ms: 182,
      finished: false,
    },
    {
      request_id: 'req-live-stream-02',
      virtual_key_name: 'Coding Agent Worker',
      client_format: 'anthropic',
      requested_model: 'claude-3-7-sonnet',
      route_name: 'fast-interactive',
      phase: 'streaming',
      commit_state: 'committed',
      fallback_hops: 0,
      retry_count: 0,
      input_tokens: 4210,
      output_tokens: 340,
      status: 200,
      latency_ms: 680,
      ttft_ms: 215,
      finished: false,
    },
  ],
  auditLogs: [
    {
      id: 'aud-001',
      timestamp: new Date(Date.now() - 1000 * 600).toISOString(),
      operator: 'admin',
      action: 'route_created',
      resource_type: 'route',
      resource_id: 'route-interactive-fast',
      details: 'Added fallback target prov-openai (gpt-4o) with weight 100',
      ip_address: '127.0.0.1',
    },
    {
      id: 'aud-002',
      timestamp: new Date(Date.now() - 1000 * 3600).toISOString(),
      operator: 'admin',
      action: 'virtual_key_created',
      resource_type: 'key',
      resource_id: 'key-ai-agent',
      details: 'Created virtual key for DevEx Engineering',
      ip_address: '127.0.0.1',
    },
  ],
  metrics: {
    active_keys: 3,
    total_keys: 3,
    active_routes: 2,
    total_routes: 2,
    healthy_providers: 3,
    total_providers: 3,
    healthy_accounts: 5,
    total_accounts: 5,
    requests_today: 18420,
    requests_this_month: 309500,
    tokens_today: 14200000,
    tokens_this_month: 152550000,
    total_spend_usd: 1735.1,
    spend_today_usd: 73.77,
    spend_this_month_usd: 1735.1,
    avg_latency_ms: 412,
    avg_ttft_ms: 198,
    error_rate: 0.002,
    active_streams: 2,
    circuit_breakers_open: 0,
    cache_hit_ratio: 0.38,
  },
  runtimeHealth: {
    window: '1h',
    telemetry: [
      {
        scope: 'model',
        target: 'claude-3-7-sonnet-20250219',
        requests: 412,
        success: 410,
        client_4xx: 2,
        server_5xx: 0,
        connection_errors: 0,
        timeouts: 0,
        adaptive_saturation: 0.02,
        provider_circuit_rejects: 0,
        ttft_p50_ms: 180,
        ttft_p95_ms: 320,
        ttft_p99_ms: 540,
        duration_p50_ms: 650,
        duration_p95_ms: 1450,
        duration_p99_ms: 2200,
      },
      {
        scope: 'model',
        target: 'gpt-4o',
        requests: 285,
        success: 284,
        client_4xx: 1,
        server_5xx: 0,
        connection_errors: 0,
        timeouts: 0,
        adaptive_saturation: 0.01,
        provider_circuit_rejects: 0,
        ttft_p50_ms: 210,
        ttft_p95_ms: 420,
        ttft_p99_ms: 680,
        duration_p50_ms: 820,
        duration_p95_ms: 1800,
        duration_p99_ms: 2900,
      },
    ],
    provider_circuits: [
      {
        provider_id: 'prov-anthropic',
        provider_name: 'Anthropic Direct',
        state: 'closed',
        failure_count: 0,
        success_count: 410,
        consecutive_failures: 0,
        last_failure_at: null,
        last_success_at: new Date().toISOString(),
      },
      {
        provider_id: 'prov-openai',
        provider_name: 'OpenAI Production',
        state: 'closed',
        failure_count: 0,
        success_count: 284,
        consecutive_failures: 0,
        last_failure_at: null,
        last_success_at: new Date().toISOString(),
      },
    ],
    quota: [
      {
        account_id: 'acc-anthropic-primary',
        account_name: 'Anthropic Tier 4 Primary',
        provider_name: 'Anthropic Direct',
        rpm_limit: 5000,
        rpm_used: 120,
        tpm_limit: 400000,
        tpm_used: 48000,
        daily_spend_limit_usd: 500,
        daily_spend_usd: 84.2,
        monthly_spend_limit_usd: 10000,
        monthly_spend_usd: 1240.0,
        resets_at: new Date(Date.now() + 86400000 * 2).toISOString(),
      },
    ],
    dropped: { queue: 0, persistence: 0 },
  },
  plugins: [
    {
      id: 'antigravity-oauth',
      name: 'Google Antigravity OAuth',
      version: '1.2.0',
      plugin_api_major: 1,
      sha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
      signature: 'verified',
      status: 'enabled',
      provides: [
        { capability: 'provider_adapter', name: 'Google Cloud Code Adapter' },
        { capability: 'credential_strategy', name: 'OAuth 2.0 PKCE' },
        { capability: 'model_source', name: 'Gemini Models Discovery' },
      ],
      integrations: [
        {
          id: 'antigravity',
          name: 'Antigravity Workspace',
          description: 'Access Gemini Flash/Pro reasoning models via enterprise OAuth credential.',
          provider_adapter: 'antigravity-oauth',
          credential_strategy: 'antigravity-oauth',
          auth_flow: 'google-oauth',
          credential_mode: 'auth_flow',
          model_source: 'antigravity-oauth',
          provider: {
            base_url: 'https://daily-cloudcode-pa.googleapis.com',
            wire_format: 'plugin',
            auth_scheme: 'bearer',
            extra_headers: {},
            timeout_ms: 120000,
            capability_mode: 'strict',
            follow_redirects: true,
            credential_hosts: ['accounts.google.com', 'oauth2.googleapis.com'],
          },
        },
      ],
      ui: {
        actions: [
          {
            id: 'connect',
            label: 'Connect Google Account',
            kind: 'auth',
            integration: 'antigravity',
            description: 'Enroll or refresh an Antigravity OAuth credential.',
          },
        ],
        settings: [],
      },
      permissions: {
        network_hosts: ['daily-cloudcode-pa.googleapis.com', 'accounts.google.com', 'oauth2.googleapis.com'],
        credential_scopes: ['https://www.googleapis.com/auth/cloud-platform'],
        credential_read: true,
      },
      limits: {
        memory: '64 MiB',
        wall_time_ms: 30000,
        max_outbound_requests: 8,
        max_http_body: '8 MiB',
        storage: 'none',
      },
      routing_facts_mode: 'cached',
      routing_facts_refresh_ms: 300000,
    },
  ],
  exportFiles: [
    { name: 'usage-2026-09-30.jsonl', day: '2026-09-30', kind: 'jsonl', bytes: 245100 },
    { name: 'usage-2026-09-30.csv', day: '2026-09-30', kind: 'csv', bytes: 98400 },
    { name: 'usage-2026-09-29.jsonl', day: '2026-09-29', kind: 'jsonl', bytes: 231400 },
    { name: 'usage-2026-09-29.csv', day: '2026-09-29', kind: 'csv', bytes: 92100 },
  ],
  exportDays: [
    { day: '2026-09-30', requests: 18420, tokens: 14200000 },
    { day: '2026-09-29', requests: 17180, tokens: 13850000 },
    { day: '2026-09-28', requests: 16540, tokens: 12900000 },
  ],
};
