import type { ScenarioState } from '../types.ts';
import { healthyScenario } from './healthy.ts';

const extraProviders = [
  {
    id: 'prov-azure-openai',
    name: 'Azure OpenAI Enterprise East US',
    base_url: 'https://kinetix-prod.openai.azure.com',
    wire_format: 'openai',
    auth_scheme: 'custom_header',
    custom_header_name: 'api-key',
    status: 'healthy',
    last_ping_ms: 82,
    models_count: 4,
    accounts_count: 2,
    credential_mode: 'manual',
    timeout_ms: 60000,
    capability_mode: 'strict',
    credential_hosts: 'kinetix-prod.openai.azure.com',
    follow_redirects: true,
  },
  {
    id: 'prov-aws-bedrock',
    name: 'AWS Bedrock Global Gateway',
    base_url: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 110,
    models_count: 6,
    accounts_count: 2,
    credential_mode: 'manual',
    timeout_ms: 60000,
    capability_mode: 'strict',
    credential_hosts: 'bedrock-runtime.us-east-1.amazonaws.com',
    follow_redirects: true,
  },
  {
    id: 'prov-deepseek',
    name: 'DeepSeek Direct Official API',
    base_url: 'https://api.deepseek.com',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 290,
    models_count: 2,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 120000,
    capability_mode: 'strict',
    credential_hosts: 'api.deepseek.com',
    follow_redirects: true,
  },
  {
    id: 'prov-groq',
    name: 'Groq LPUs Ultra-Fast Inferencing',
    base_url: 'https://api.groq.com/openai/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 38,
    models_count: 4,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 15000,
    capability_mode: 'strict',
    credential_hosts: 'api.groq.com',
    follow_redirects: true,
  },
  {
    id: 'prov-together',
    name: 'Together AI High-Density Compute',
    base_url: 'https://api.together.xyz/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 95,
    models_count: 8,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 60000,
    capability_mode: 'permissive',
    credential_hosts: 'api.together.xyz',
    follow_redirects: true,
  },
  {
    id: 'prov-mistral',
    name: 'Mistral AI Platform Europe',
    base_url: 'https://api.mistral.ai/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 164,
    models_count: 5,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 45000,
    capability_mode: 'strict',
    credential_hosts: 'api.mistral.ai',
    follow_redirects: true,
  },
  {
    id: 'prov-cohere',
    name: 'Cohere North Command & Embed',
    base_url: 'https://api.cohere.com/v2',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 132,
    models_count: 3,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 45000,
    capability_mode: 'strict',
    credential_hosts: 'api.cohere.com',
    follow_redirects: true,
  },
  {
    id: 'prov-fireworks',
    name: 'Fireworks AI Fine-Tuned Serving',
    base_url: 'https://api.fireworks.ai/inference/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 78,
    models_count: 6,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 30000,
    capability_mode: 'permissive',
    credential_hosts: 'api.fireworks.ai',
    follow_redirects: true,
  },
  {
    id: 'prov-perplexity',
    name: 'Perplexity Search-Grounded AI',
    base_url: 'https://api.perplexity.ai',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 210,
    models_count: 2,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 60000,
    capability_mode: 'strict',
    credential_hosts: 'api.perplexity.ai',
    follow_redirects: true,
  },
  {
    id: 'prov-cerebras',
    name: 'Cerebras Wafer-Scale Engine Cluster',
    base_url: 'https://api.cerebras.ai/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 22,
    models_count: 2,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 10000,
    capability_mode: 'strict',
    credential_hosts: 'api.cerebras.ai',
    follow_redirects: true,
  },
  {
    id: 'prov-xai',
    name: 'xAI Grok Supercomputing Cluster',
    base_url: 'https://api.x.ai/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 145,
    models_count: 2,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 60000,
    capability_mode: 'strict',
    credential_hosts: 'api.x.ai',
    follow_redirects: true,
  },
  {
    id: 'prov-ollama-local',
    name: 'Local Ollama High-Sec Workstation',
    base_url: 'http://10.0.80.5:11434/v1',
    wire_format: 'openai',
    auth_scheme: 'none',
    status: 'healthy',
    last_ping_ms: 8,
    models_count: 3,
    accounts_count: 1,
    credential_mode: 'manual',
    timeout_ms: 90000,
    capability_mode: 'permissive',
    credential_hosts: '10.0.80.5',
    follow_redirects: false,
  },
  {
    id: 'prov-vllm-datacenter',
    name: 'Internal vLLM H100 GPU Farm',
    base_url: 'https://vllm-cluster.corp.internal/v1',
    wire_format: 'openai',
    auth_scheme: 'bearer',
    status: 'healthy',
    last_ping_ms: 14,
    models_count: 4,
    accounts_count: 2,
    credential_mode: 'manual',
    timeout_ms: 45000,
    capability_mode: 'permissive',
    credential_hosts: 'vllm-cluster.corp.internal',
    follow_redirects: false,
  },
];

export const largeProviderSetScenario: ScenarioState = {
  ...healthyScenario,
  id: 'large-provider-set',
  name: 'Multi-Cloud Large Provider Fleet',
  description: '16 diverse upstream providers spanning proprietary APIs, hyperscalers, open-weights hosting, and private on-prem clusters.',
  badge: '16 Providers',
  badgeColor: 'purple',
  providers: [...healthyScenario.providers, ...extraProviders],
  metrics: {
    ...healthyScenario.metrics,
    healthy_providers: 16,
    total_providers: 16,
    healthy_accounts: 22,
    total_accounts: 22,
  },
};
